# Generated by Django 4.1.7 on 2023-04-16 11:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "appointment_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("appointment_date", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Clients",
            fields=[
                ("client_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salons",
            fields=[
                ("salon_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=300)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("website", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stylists",
            fields=[
                ("stylist_id", models.IntegerField(primary_key=True, serialize=False)),
                ("stylist_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "salon_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.salons"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                ("service_id", models.IntegerField(primary_key=True, serialize=False)),
                ("service_name", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "salon_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.salons"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                ("review_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30)),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(blank=True)),
                ("review_date", models.DateTimeField()),
                (
                    "salon_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.salons"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("payment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("payment_datetime", models.DateTimeField()),
                (
                    "appointment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.appointments",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointments",
            name="client_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.clients"
            ),
        ),
        migrations.AddField(
            model_name="appointments",
            name="service_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.services"
            ),
        ),
    ]
