# Generated by Django 4.1.7 on 2023-04-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_salons_last_login_salons_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salons',
            name='last_login',
        ),
        migrations.AddField(
            model_name='salons',
            name='email',
            field=models.EmailField(default='blank', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salons',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
