# Generated by Django 4.1.7 on 2023-04-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_salons_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salons',
            name='last_login',
        ),
    ]
